server:
  port: 9012
spring:
  application:
    name: heufei-manager #指定服务名
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/ #eureka客户端和服务器端交互的地址,6868是eureka服务的地址
  instance:
    prefer-ip-address: true  #能否跨服务器访问（就是说访问另一个服务）

zuul:
  sensitive-headers:
  routes:
    hyf-article:
      path: /article/**
      url: http://localhost:9004/article
#      serviceId: hyf-a rticle

    hyf-friend:
      path: /friend/**
      url: http://localhost:9010/friend
#      serviceId: hyf-friend

    hyf-base:
      path: /label/**
      url: http://localhost:9000/label
#      serviceId: hyf-base

    hyf-question:
      path: /problem/**, /reply/**
#      url: http://localhost:9003/problem
      serviceId: hyf-question

    hyf-recruit: #招聘
      path: /recruit/**, /enterprise/**
#      url: http://localhost:9002/recruit
      serviceId: hyf-recruit

    hyf-spit: #吐槽
      path: /spit/**
      url: http://localhost:9006/spit
#      serviceId: hyf-spit

    hyf-user:
      path: /user/**
      url: http://localhost:9008/user
#      serviceId: hyf-user

    hyf-gathering:
      path: /gathering/**
      url: http://localhost:9005/gathering
  #      serviceId: hyf-gathering


  host:
    connect-timeout-millis: 600000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 600000   #socket超时

#ribbon:        #设置ribbon的超时时间小于zuul的超时时间
#  ReadTimeout: 10000
#  ConnectTimeout: 10000


feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 600000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 100000

jwt:
  config:
    key: heyufei
    ttl: 3600000000
