server: 
  port: 9001
spring: 
  application:  
    name: fly-[path_3] #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.24.145.157:3306/fly_school?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: Jsu123456.
  jpa: 
    database: MySQL
    show-sql: true
